title: Joshua Dowding - Writer; Developer
author: Joshua Dowding
description: Joshua Dowding's personal blog and portfolio.
email: joshuadowding@outlook.com

#lang: en-GB
locale: en-GB
timezone: GB

url: https://joshuadowding.com
baseurl: ""
permalink: /:title/

destination: ./dist/
source: ./src/
include: ['_pages']
exclude: ['bin/*', 'vendor/', 'node_modules/', 'gemfile', 'gemfile.lock', 'README.md']

safe: false
encoding: utf-8
rvm: 2.7.2

plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0

sitemap: true
permalink: pretty

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

sass:
  sass_dir: ./_sass/
  style: compressed
